apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: azure-webapp
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: azure-webapp
    spec:
      containers:
        - image: changregistry.azurecr.io/sum-webapp:v1.0.1
          imagePullPolicy: Always
          name: sum-webapp
          env:
            - name: SUM_LOGIC_API_URL
              value: "http://azure-logic"
            - name: SUM_WEBAPP_LB_URL
              value: "http://40.117.76.78"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: changregistry