apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: azure-logic
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: azure-logic
    spec:
      containers:
        - image: changregistry.azurecr.io/sum-logic:v1.0.0
          imagePullPolicy: Always
          name: sum-logic
          ports:
            - containerPort: 7070
      imagePullSecrets:
        - name: changregistry